services:
  postgres:
    image: postgres:12
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: api8inf349
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:5
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  postgres-data:
